version: 2.1

jobs:
# name of the job
  build:
  # enviroment host for docker, this where the code will be built
    docker:
      - image: cimg/node:17.9.0

    steps:
    # checkout pull the code from github
      - checkout
      - run:
          name: "install dependencies"
          command: "npm install"
      

workflows:
  putting_together_the_project:
    jobs:
      - build
