version: 2.1

jobs:
# name of the job
  build:
  # enviroment host for docker, this where the code will be built
     machine:
       image: ubuntu-2004:202201-02
       docker_layer_caching: true

     steps:
    # checkout pull the code from github
      - checkout
      - run:
          name: "install dependencies"
          command: "npm install"
      - run:
          name: "Docker build"
          command: |
               docker build -t node-app-circleci:v1.0.2 .
      - run:
          name: "Docker tag"
          command: |
               docker tag node-app-circleci:v1.0.2 rayan147/node-app-circleci:v1.0.3
      - run:
          name: "Docker run and grab the container id"
          command: |
               docker run --name node-app-container node-app-circleci:v1.0.2
      - run:
          name: "Container id variable"
          command: |
               export CONTAINER_ID=$(docker ps -aqf "name=node-app-container")
      - run:
          name: "Docker commit"
          command: |
               docker commit $CONTAINER_ID rayan147/node-app-circleci:v1.0.3
      - run:
          name: "Docker push"
          command: |
               docker push rayan147/node-app-circleci:v1.0.3


workflows:
  putting_together_the_project:
    jobs:
      - build
