version: 2.1

jobs:
# name of the job
  build:
  # enviroment host for docker, this where the code will be built
     machine:
       image: ubuntu-2004:202201-02
       docker_layer_caching: true
       
     steps:
    # checkout pull the code from github
      - checkout
      - run:
          name: "install dependencies"
          command: "npm install"
      - run:
          name: "docker build"
          command: |
               docker build -t node-app-circleci:v1.0.2 .
      

workflows:
  putting_together_the_project:
    jobs:
      - build
